### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by FlumSM** [ericmurphyxyz/userChrome.css#2]
Hi, the latest Firefox update broke this css, I was wondering if you'd be able to fix it. I've been trying to fix it myself for an hour but I can't get to work properly.
here's a screenshot of the problem.
![image](https://github.com/ericmurphyxyz/userChrome.css/assets/149193120/dfc1e6d9-44a5-4901-b601-e17ca02d8849)
Sorry for the inconvenience.

**Comment by fcristallocagnoli** [comment]
I had the same problem, I've just opened the PR #3  with a possible solution that  worked out for me. Hope it works for you as well.

**Comment by FlumSM** [comment]
It works, thank you very much!
